[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[[redirects]]
  from = "/*"
  to = "/_netlify_edge_functions_bridge"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"